version: '2'

services:
  pmm-data:
    build: .
    image: percona/pmm-server
    container_name: pmm-data
    volumes:
      - /var/lib/mysql
      - /opt/prometheus/data
      - /opt/consul-data
    entrypoint: /bin/true

  pmm-server:
    build: .
    container_name: pmm-server
    image: percona/pmm-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - pmm-data
#    volumes:
#      - /root/docker_shared_volumes/ssl:/etc/nginx/ssl
    environment:
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=262144
      - METRICS_RESOLUTION=1s
      - ORCHESTRATOR_USER=orc_client_user
      - ORCHESTRATOR_PASSWORD=orc_client_password
#      - SERVER_USER=pmm
#      - SERVER_PASSWORD=abc123
